name: napari-taturtle-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - napari
  - pyqt
  - numpy
  - scikit-image
  - magicgui
  - qtpy
  - tifffile
  - h5py
  - scipy
  - pip
  - pip:
    - simpleitk
    - -e ../taturtle
    - -e ../squirrel
