name: napari-taturtle-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - napari
  - pyqt
  - numpy
  - scikit-image
  - magicgui
  - qtpy
  - tifffile
  - h5py
  - scipy
  - matplotlib
  - pip
  - pip:
    - SimpleITK-SimpleElastix
    - git+https://github.com/vib-bic-code/taturtle
    - git+https://github.com/jhennies/squirrel
